import { EnvironmentOverview, WorkspaceInspection, SystemSpecsReport, LiveSystemMetrics, StartupProgramItem, LargeFileItem, InstalledAppItem, DuplicateReport } from '../types/entropy';

export const MOCK_ENTROPY_INSPECTION: WorkspaceInspection = {
  workspace: {
    id: "project:C:\\Users\\pc\\Desktop\\entropy",
    name: "entropy",
    path: "C:\\Users\\pc\\Desktop\\entropy",
    project_type: "python",
    total_size_bytes: 763120,
    created: 1789868689.27,
    last_modified: Date.now() / 1000 - 120,
    runtime_version_hint: null,
  },
  state: {
    label: "Active / Current Codebase",
    summary: "Recent modifications or commits observed within the last 30 days.",
    category: "active",
    why_factors: [
      "10 active processes running directly from this directory (including python.exe, powershell.exe, pyrefly.exe)",
      "Uncommitted local modifications present in working tree",
      "Git commit observed 14m ago on branch 'main'",
      "Active process execution on Python 3.14.3 runtime"
    ],
    primary_uncertainty: "Uncommitted changes are detected, but Entropy cannot determine whether they are intentional code changes or generated residue.",
  },
  connections: {
    git: {
      entity_id: "git:C:\\Users\\pc\\Desktop\\entropy",
      repo_path: "C:\\Users\\pc\\Desktop\\entropy",
      current_branch: "main",
      is_clean: false,
      commit_count: 10,
      last_commit_timestamp: Date.now() / 1000 - 840,
      last_commit_hash: "c3d288e",
      last_commit_message: "Complete Phase 9 v0.1 Productization",
      last_commit_author: "wacim <wacim@entropy.local>",
      has_uncommitted_changes: true,
      has_remote: true,
      remote_host: "github.com",
      remote_repo_id: "github.com/wacim-abdellli/entropy",
      repo_size_bytes: 217254,
      is_worktree: false,
      worktree_parent_repo: null,
      dirty_files: [
        { status: "modified", path: "desktop/src/components/WorkspaceView.tsx" },
        { status: "modified", path: "report/inspect.py" },
        { status: "untracked", path: "desktop/src/components/EvidencePanel.tsx" },
      ],
      secret_issues: [
        { path: ".env", name: ".env", category: "env", status: "protected", risk: "safe", action: null },
      ],
    },
    processes: [
      {
        entity_id: "proc:20116_1789888590",
        pid: 20116,
        name: "python.exe",
        exe_path: "C:\\Python314\\python.exe",
        cwd: "C:\\Users\\pc\\Desktop\\entropy",
        parent_pid: 1500,
        create_time: Date.now() / 1000 - 300,
        memory_bytes: 25600000,
        cpu_percent: 0.8,
        cmdline_preview: "python.exe scan.py inspect . --json",
        is_shell: false,
      },
      {
        entity_id: "proc:12340_1789881865",
        pid: 12340,
        name: "pyrefly.exe",
        exe_path: "C:\\Users\\pc\\AppData\\Local\\Programs\\pyrefly\\pyrefly.exe",
        cwd: "C:\\Users\\pc\\Desktop\\entropy",
        parent_pid: 13348,
        create_time: Date.now() / 1000 - 2400,
        memory_bytes: 83048960,
        cpu_percent: 0.2,
        cmdline_preview: "pyrefly.exe --lsp",
        is_shell: false,
      },
      {
        entity_id: "proc:1500_1789888590",
        pid: 1500,
        name: "powershell.exe",
        exe_path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
        cwd: "C:\\Users\\pc\\Desktop\\entropy",
        parent_pid: 13348,
        create_time: Date.now() / 1000 - 1200,
        memory_bytes: 85249024,
        cpu_percent: 0.0,
        cmdline_preview: "powershell.exe",
        is_shell: true,
      },
      {
        entity_id: "proc:13348_1789870184",
        pid: 13348,
        name: "Antigravity IDE.exe",
        exe_path: "C:\\Program Files\\Antigravity\\Antigravity IDE.exe",
        cwd: "C:\\Users\\pc\\Desktop\\entropy",
        parent_pid: 1024,
        create_time: Date.now() / 1000 - 7200,
        memory_bytes: 105172992,
        cpu_percent: 1.4,
        cmdline_preview: "Antigravity IDE.exe C:\\Users\\pc\\Desktop\\entropy",
        is_shell: false,
      },
    ],
    runtimes: [
      {
        entity_id: "runtime:python_3.14.3",
        name: "python",
        version: "3.14.3",
        executable_path: "C:\\Python314\\python.exe",
        install_path: "C:\\Python314",
        is_system: true,
      },
      {
        entity_id: "runtime:node_24.16.0",
        name: "node",
        version: "24.16.0",
        executable_path: "C:\\Program Files\\nodejs\\node.exe",
        install_path: "C:\\Program Files\\nodejs",
        is_system: true,
      },
    ],
    docker: [],
    dependencies: [],
    caches: [
      {
        entity_id: "cache:pip",
        category: "pip",
        path: "C:\\Users\\pc\\AppData\\Local\\pip\\cache",
        size_bytes: 84192000,
        entry_count: 38,
        last_modified: Date.now() / 1000 - 3600,
        is_shared: true,
        scope: "shared_system",
        scope_explanation: "Shared across projects on this machine. (Not isolated to this workspace)",
      }
    ],
    process_groups: [],
  },
  entities: [
    {
      entity_id: "project:C:\\Users\\pc\\Desktop\\entropy",
      path: "C:\\Users\\pc\\Desktop\\entropy",
      project_type: "python",
      total_size_bytes: 763120,
    },
    {
      entity_id: "git:C:\\Users\\pc\\Desktop\\entropy",
      current_branch: "main",
      remote_repo_id: "github.com/wacim-abdellli/entropy",
    },
    {
      entity_id: "proc:20116_1789888590",
      name: "python.exe",
      pid: 20116,
    },
    {
      entity_id: "proc:12340_1789881865",
      name: "pyrefly.exe",
      pid: 12340,
    },
    {
      entity_id: "proc:1500_1789888590",
      name: "powershell.exe",
      pid: 1500,
    },
    {
      entity_id: "runtime:python_3.14.3",
      name: "python",
      version: "3.14.3",
    },
  ],
  relationships: [
    {
      source_id: "project:C:\\Users\\pc\\Desktop\\entropy",
      target_id: "git:C:\\Users\\pc\\Desktop\\entropy",
      rel_type: "contains",
      observability: "directly_observable",
      evidence: ".git repository located directly at C:\\Users\\pc\\Desktop\\entropy",
    },
    {
      source_id: "proc:20116_1789888590",
      target_id: "project:C:\\Users\\pc\\Desktop\\entropy",
      rel_type: "runs_from",
      observability: "strongly_inferable",
      evidence: "Process 'python.exe' (PID 20116) working directory (C:\\Users\\pc\\Desktop\\entropy) is within project",
    },
    {
      source_id: "proc:12340_1789881865",
      target_id: "project:C:\\Users\\pc\\Desktop\\entropy",
      rel_type: "runs_from",
      observability: "strongly_inferable",
      evidence: "Process 'pyrefly.exe' (PID 12340) working directory (C:\\Users\\pc\\Desktop\\entropy) is within project",
    },
    {
      source_id: "proc:1500_1789888590",
      target_id: "project:C:\\Users\\pc\\Desktop\\entropy",
      rel_type: "runs_from",
      observability: "strongly_inferable",
      evidence: "Process 'powershell.exe' (PID 1500) working directory (C:\\Users\\pc\\Desktop\\entropy) is within project",
    },
    {
      source_id: "proc:20116_1789888590",
      target_id: "runtime:python_3.14.3",
      rel_type: "runs_on",
      observability: "strongly_inferable",
      evidence: "Executable path matches runtime installation python 3.14.3",
    },
  ],
  findings: [],
  evidence: [
    {
      category: "git_branch",
      label: "Git Branch",
      value: "main",
      detail: "Remote: github.com/wacim-abdellli/entropy",
      verified: true,
    },
    {
      category: "git_commit",
      label: "Last Commit",
      value: "14m ago",
      detail: "10 commits in HEAD history",
      timestamp: Date.now() / 1000 - 840,
      verified: true,
    },
    {
      category: "git_working_tree",
      label: "Working Tree",
      value: "Uncommitted local modifications",
      detail: "status --porcelain checked",
      verified: true,
    },
    {
      category: "process",
      label: "Process: python.exe",
      value: "PID 20116 (Active Process)",
      detail: "cwd=C:\\Users\\pc\\Desktop\\entropy RSS=24.4 MB",
      verified: true,
    },
    {
      category: "process",
      label: "Process: pyrefly.exe",
      value: "PID 12340 (Language Server)",
      detail: "cwd=c:\\Users\\pc\\Desktop\\entropy RSS=79.2 MB",
      verified: true,
    },
    {
      category: "process",
      label: "Process: powershell.exe",
      value: "PID 1500 (Interactive Shell)",
      detail: "cwd=c:\\Users\\pc\\Desktop\\entropy RSS=81.3 MB",
      verified: true,
    },
  ],
  primary_uncertainty: "Uncommitted changes are detected, but Entropy cannot determine whether they are intentional code changes or generated residue.",
  uncertainties: [
    "Local modifications exist, but Entropy cannot determine whether they represent valuable human work or generated artifacts.",
    "Process execution confirms running code, but Entropy cannot determine if it is an active developer session or an unattended background service."
  ],
  action_boundary: {
    read_only: true,
    notice: "Entropy is read-only and performs zero automatic cleanup or remediation.",
    verification_steps: [
      "Run 'git status' and 'git diff' inside this directory to inspect modified/untracked files.",
      "Verify whether changes are valuable code edits or disposable build logs/residue.",
      "Check if the current branch exists on remote ('git branch -r') before deleting or archiving."
    ],
  },
  metadata: {
    scan_duration_ms: 182,
    engine_version: "0.1.0",
    timestamp: Date.now() / 1000,
    hostname: "DESKTOP-OQLTNEG",
    root: "C:\\Users\\pc\\Desktop\\entropy",
  },
};

export const MOCK_TALIB_INSPECTION: WorkspaceInspection = {
  workspace: {
    id: "project:C:\\Users\\pc\\Desktop\\talib_ilm-main",
    name: "talib_ilm-main",
    path: "C:\\Users\\pc\\Desktop\\talib_ilm-main",
    project_type: "python",
    total_size_bytes: 4210500,
    created: 1788000000,
    last_modified: 1788500000,
    runtime_version_hint: "3.11",
  },
  state: {
    label: "Stale / Inactive Project",
    summary: "No filesystem activity or commits observed in over 60 days.",
    category: "dormant",
    why_factors: [
      "No filesystem modifications in 72 days",
      "Zero active processes associated with this directory",
      "No active Docker container or background service attached"
    ],
  },
  connections: {
    git: null,
    processes: [],
    runtimes: [
      {
        entity_id: "runtime:python_3.14.3",
        name: "python",
        version: "3.14.3",
        executable_path: "C:\\Python314\\python.exe",
        install_path: "C:\\Python314",
        is_system: true,
      }
    ],
    docker: [],
    dependencies: [
      {
        entity_id: "dep:venv",
        dep_type: "venv",
        path: "C:\\Users\\pc\\Desktop\\talib_ilm-main\\.venv",
        size_bytes: 184500000,
        package_count: 42,
        is_stale: true,
      }
    ],
    caches: [],
  },
  entities: [
    {
      entity_id: "project:C:\\Users\\pc\\Desktop\\talib_ilm-main",
      path: "C:\\Users\\pc\\Desktop\\talib_ilm-main",
      project_type: "python",
      total_size_bytes: 4210500,
    },
    {
      entity_id: "dep:venv",
      path: "C:\\Users\\pc\\Desktop\\talib_ilm-main\\.venv",
      size_bytes: 184500000,
    }
  ],
  relationships: [
    {
      source_id: "project:C:\\Users\\pc\\Desktop\\talib_ilm-main",
      target_id: "dep:venv",
      rel_type: "contains",
      observability: "directly_observable",
      evidence: "Virtualenv directory .venv directly inside project folder",
    }
  ],
  findings: [
    {
      id: "dormant_large_dependency_environment",
      title: "Inactive Workspace Retaining 184 MB Virtual Environment",
      category: "resource_retention",
      severity: "low",
      evidence: [
        "Workspace has had zero activity for 72 days",
        ".venv occupies 184.5 MB on disk",
        "Zero running processes referencing this virtualenv"
      ],
      explanation: "A dormant project retains local virtual environment packages that could easily be recreated from requirements.txt if resumed.",
      recommendation: "If you are not currently actively developing talib_ilm-main, you can safely remove .venv and recreate it with 'python -m venv .venv && pip install -r requirements.txt' when needed.",
      action_boundary: "Entropy does not delete virtualenvs. You can manually inspect requirements.txt first.",
      entities_involved: ["project:C:\\Users\\pc\\Desktop\\talib_ilm-main", "dep:venv"],
      confidence: 0.95,
    }
  ],
  evidence: [
    {
      category: "git_metadata",
      label: "Git Repository",
      value: "Unversioned Directory",
      detail: "No .git folder located",
      verified: true,
    },
    {
      category: "filesystem_mtime",
      label: "Filesystem Mtime",
      value: "72 days ago",
      timestamp: 1788500000,
      verified: true,
    },
  ],
  uncertainties: [
    "Unversioned codebase: without Git, history and previous branches cannot be inspected."
  ],
  action_boundary: {
    read_only: true,
    notice: "Entropy is read-only and performs zero automatic cleanup or remediation.",
    verification_steps: [
      "Check if any personal notes or uncommitted scripts exist inside this folder before archiving."
    ],
  },
  metadata: {
    scan_duration_ms: 110,
    engine_version: "0.1.0",
    timestamp: Date.now() / 1000,
    hostname: "DESKTOP-OQLTNEG",
    root: "C:\\Users\\pc\\Desktop\\talib_ilm-main",
  },
};

export const MOCK_AFTERSALES_INSPECTION: WorkspaceInspection = {
  workspace: {
    id: "project:C:\\Users\\pc\\source\\repos\\AfterSalesManagement",
    name: "AfterSalesManagement",
    path: "C:\\Users\\pc\\source\\repos\\AfterSalesManagement",
    project_type: "node",
    total_size_bytes: 142000000,
    created: 1785000000,
    last_modified: 1787000000,
    runtime_version_hint: "20.x",
  },
  state: {
    label: "Inactive / Clean Codebase",
    summary: "Uncommitted changes exist on feature branch, but workspace has had no execution for 45 days.",
    category: "inactive",
    why_factors: [
      "Branch 'main' has modified files not yet committed",
      "Last commit was observed 4 months ago",
      "No active processes running from this workspace"
    ],
  },
  connections: {
    git: {
      entity_id: "git:C:\\Users\\pc\\source\\repos\\AfterSalesManagement",
      repo_path: "C:\\Users\\pc\\source\\repos\\AfterSalesManagement",
      current_branch: "main",
      is_clean: false,
      commit_count: 48,
      last_commit_timestamp: 1787000000,
      last_commit_hash: "a49b21f",
      last_commit_message: "WIP: add RMA tracking status endpoint",
      last_commit_author: "wacim <wacim@entropy.local>",
      has_uncommitted_changes: true,
      has_remote: true,
      remote_host: "github.com",
      remote_repo_id: "github.com/company/AfterSalesManagement",
      repo_size_bytes: 12400000,
      is_worktree: false,
      worktree_parent_repo: null,
      unprotected_env_files: [".env.local"],
      secret_issues: [
        { path: "credentials.json", name: "credentials.json", category: "credential", status: "tracked", risk: "high", action: "untrack" },
        { path: ".env.local", name: ".env.local", category: "env", status: "unignored", risk: "medium", action: "ignore" },
        { path: ".env", name: ".env", category: "env", status: "protected", risk: "safe", action: null },
      ],
    },
    processes: [],
    runtimes: [
      {
        entity_id: "runtime:node_24.16.0",
        name: "node",
        version: "24.16.0",
        executable_path: "C:\\Program Files\\nodejs\\node.exe",
        install_path: "C:\\Program Files\\nodejs",
        is_system: true,
      }
    ],
    docker: [],
    dependencies: [
      {
        entity_id: "dep:node_modules",
        dep_type: "node_modules",
        path: "C:\\Users\\pc\\source\\repos\\AfterSalesManagement\\node_modules",
        size_bytes: 128000000,
        package_count: 890,
        is_stale: true,
      }
    ],
    caches: [
      {
        entity_id: "cache:npm",
        category: "npm",
        path: "C:\\Users\\pc\\AppData\\Local\\npm-cache",
        size_bytes: 245000000,
        entry_count: 340,
        last_modified: 1787000000,
        is_shared: true,
        scope: "shared_system",
        scope_explanation: "Shared across projects on this machine. (Not isolated to this workspace)",
      }
    ],
  },
  entities: [
    {
      entity_id: "project:C:\\Users\\pc\\Desktop\\AfterSalesManagement",
      path: "C:\\Users\\pc\\Desktop\\AfterSalesManagement",
      project_type: "node",
    },
    {
      entity_id: "git:C:\\Users\\pc\\Desktop\\AfterSalesManagement",
      current_branch: "feature/rma-tracker",
    }
  ],
  relationships: [
    {
      source_id: "project:C:\\Users\\pc\\Desktop\\AfterSalesManagement",
      target_id: "git:C:\\Users\\pc\\Desktop\\AfterSalesManagement",
      rel_type: "contains",
      observability: "directly_observable",
      evidence: ".git folder present",
    }
  ],
  findings: [
    {
      id: "uncommitted_changes_stale_branch",
      title: "Uncommitted Work on Stale Feature Branch",
      category: "uncommitted_risk",
      severity: "medium",
      evidence: [
        "Feature branch 'feature/rma-tracker' has 8 modified files",
        "Last commit was 45 days ago",
        "No processes or shell sessions open in this workspace"
      ],
      explanation: "Uncommitted modifications in a dormant workspace run the risk of being lost during future branch checkouts or accidental cleanups.",
      recommendation: "Review the working tree diff using 'git diff' or 'git status'. Commit your work or create a stash.",
      action_boundary: "Entropy never modifies git repositories or working trees.",
      entities_involved: ["project:C:\\Users\\pc\\Desktop\\AfterSalesManagement", "git:C:\\Users\\pc\\Desktop\\AfterSalesManagement"],
      confidence: 0.98,
    }
  ],
  evidence: [
    {
      category: "git_branch",
      label: "Git Branch",
      value: "feature/rma-tracker",
      detail: "Remote tracking: origin/feature/rma-tracker",
      verified: true,
    },
    {
      category: "git_working_tree",
      label: "Working Tree",
      value: "8 dirty files",
      detail: "Modified files in src/controllers and src/routes",
      verified: true,
    },
  ],
  uncertainties: [
    "Entropy cannot determine if the uncommitted code is an abandoned experiment or valuable unfinished business logic."
  ],
  action_boundary: {
    read_only: true,
    notice: "Entropy is read-only and performs zero automatic cleanup or remediation.",
    verification_steps: [
      "Run 'git status' and 'git diff' to view uncommitted work.",
      "Run 'git stash' or 'git commit -m \"wip\"' if you wish to preserve it safely."
    ],
  },
  metadata: {
    scan_duration_ms: 140,
    engine_version: "0.1.0",
    timestamp: Date.now() / 1000,
    hostname: "DESKTOP-OQLTNEG",
    root: "C:\\Users\\pc\\Desktop\\AfterSalesManagement",
  },
};

export const MOCK_ENVIRONMENT_OVERVIEW: EnvironmentOverview = {
  summary: {
    total_workspaces: 3,
    active_count: 1,
    attention_count: 1,
    dormant_count: 0,
    inactive_count: 1,
    paused_count: 0,
    neutral_count: 0,
    total_processes: 12,
    total_runtimes: 3,
    total_containers: 0,
    total_caches: 2,
  },
  workspaces: [
    {
      id: "project:C:\\Users\\pc\\source\\repos\\AfterSalesManagement",
      name: "AfterSalesManagement",
      path: "C:\\Users\\pc\\source\\repos\\AfterSalesManagement",
      project_type: "node",
      total_size_bytes: 142000000,
      last_modified: 1787000000,
      state_label: "Inactive / Clean Codebase",
      state_category: "inactive",
      git_branch: "main",
      git_remote: "github.com/company/AfterSalesManagement",
      last_commit_timestamp: 1787000000,
      has_uncommitted_changes: false,
      unprotected_env_files: [".env.local"],
      secret_issues: [
        { path: "credentials.json", name: "credentials.json", category: "credential", status: "tracked", risk: "high", action: "untrack" },
        { path: ".env.local", name: ".env.local", category: "env", status: "unignored", risk: "medium", action: "ignore" },
        { path: ".env", name: ".env", category: "env", status: "protected", risk: "safe", action: null },
      ],
      process_count: 0,
    },
    {
      id: "project:C:\\Users\\pc\\Desktop\\entropy",
      name: "entropy",
      path: "C:\\Users\\pc\\Desktop\\entropy",
      project_type: "python",
      total_size_bytes: 763120,
      last_modified: Date.now() / 1000 - 120,
      state_label: "Active / Current Codebase",
      state_category: "active",
      git_branch: "main",
      git_remote: "github.com/wacim-abdellli/entropy",
      last_commit_timestamp: Date.now() / 1000 - 840,
      has_uncommitted_changes: true,
      secret_issues: [
        { path: ".env", name: ".env", category: "env", status: "protected", risk: "safe", action: null },
      ],
      process_count: 4,
    },
    {
      id: "project:C:\\Users\\pc\\Desktop\\talib_ilm-main",
      name: "talib_ilm-main",
      path: "C:\\Users\\pc\\Desktop\\talib_ilm-main",
      project_type: "python",
      total_size_bytes: 4210500,
      last_modified: 1788500000,
      state_label: "Stale / Inactive Project",
      state_category: "dormant",
      git_branch: null,
      git_remote: null,
      last_commit_timestamp: null,
      has_uncommitted_changes: false,
      process_count: 0,
    },
  ],
  system: {
    runtimes: [
      {
        entity_id: "runtime:python_3.14.3",
        name: "python",
        version: "3.14.3",
        executable_path: "C:\\Python314\\python.exe",
        install_path: "C:\\Python314",
        is_system: true,
      },
      {
        entity_id: "runtime:node_24.16.0",
        name: "node",
        version: "24.16.0",
        executable_path: "C:\\Program Files\\nodejs\\node.exe",
        install_path: "C:\\Program Files\\nodejs",
        is_system: true,
      },
      {
        entity_id: "runtime:cargo_1.98.1",
        name: "cargo",
        version: "1.98.1",
        executable_path: "C:\\Users\\pc\\.cargo\\bin\\cargo.exe",
        install_path: "C:\\Users\\pc\\.cargo",
        is_system: false,
      },
    ],
    processes: [
      {
        entity_id: "proc:20116_1789888590",
        pid: 20116,
        name: "python.exe",
        exe_path: "C:\\Python314\\python.exe",
        cwd: "C:\\Users\\pc\\Desktop\\entropy",
        parent_pid: 1500,
        create_time: Date.now() / 1000 - 300,
        memory_bytes: 25600000,
        cpu_percent: 0.8,
        cmdline_preview: "python.exe scan.py inspect . --json",
        is_shell: false,
      },
      {
        entity_id: "proc:12340_1789881865",
        pid: 12340,
        name: "pyrefly.exe",
        exe_path: "C:\\Users\\pc\\AppData\\Local\\Programs\\pyrefly\\pyrefly.exe",
        cwd: "C:\\Users\\pc\\Desktop\\entropy",
        parent_pid: 13348,
        create_time: Date.now() / 1000 - 2400,
        memory_bytes: 83048960,
        cpu_percent: 0.2,
        cmdline_preview: "pyrefly.exe --lsp",
        is_shell: false,
      },
      {
        entity_id: "proc:1500_1789888590",
        pid: 1500,
        name: "powershell.exe",
        exe_path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
        cwd: "C:\\Users\\pc\\Desktop\\entropy",
        parent_pid: 13348,
        create_time: Date.now() / 1000 - 1200,
        memory_bytes: 85249024,
        cpu_percent: 0.0,
        cmdline_preview: "powershell.exe",
        is_shell: true,
      },
      {
        entity_id: "proc:13348_1789870184",
        pid: 13348,
        name: "Antigravity IDE.exe",
        exe_path: "C:\\Program Files\\Antigravity\\Antigravity IDE.exe",
        cwd: "C:\\Users\\pc\\Desktop\\entropy",
        parent_pid: 1024,
        create_time: Date.now() / 1000 - 7200,
        memory_bytes: 105172992,
        cpu_percent: 1.4,
        cmdline_preview: "Antigravity IDE.exe C:\\Users\\pc\\Desktop\\entropy",
        is_shell: false,
      },
    ],
    containers: [],
    caches: [
      {
        entity_id: "cache:pip",
        category: "pip",
        path: "C:\\Users\\pc\\AppData\\Local\\pip\\cache",
        size_bytes: 84192000,
        entry_count: 38,
        last_modified: Date.now() / 1000 - 3600,
      },
      {
        entity_id: "cache:npm",
        category: "npm",
        path: "C:\\Users\\pc\\AppData\\Local\\npm-cache",
        size_bytes: 245000000,
        entry_count: 340,
        last_modified: 1787000000,
      },
    ],
  },
  findings: [
    {
      id: "uncommitted_changes_stale_branch",
      title: "Uncommitted Work on Stale Feature Branch",
      category: "uncommitted_risk",
      severity: "medium",
      evidence: [
        "Feature branch 'feature/rma-tracker' in 'AfterSalesManagement' has 8 uncommitted modified files",
        "Last commit occurred 45 days ago",
        "Zero active process or shell session currently open in workspace"
      ],
      explanation: "Uncommitted work on a dormant branch risks accidental loss during maintenance.",
      recommendation: "Inspect diff and commit or stash changes before moving workspace.",
      entities_involved: ["project:C:\\Users\\pc\\Desktop\\AfterSalesManagement"],
      confidence: 0.98,
    },
    {
      id: "dormant_large_dependency_environment",
      title: "Inactive Workspace Retaining 184 MB Virtual Environment",
      category: "resource_retention",
      severity: "low",
      evidence: [
        "Workspace 'talib_ilm-main' inactive for 72 days",
        ".venv occupies 184.5 MB",
        "No processes running"
      ],
      explanation: "A dormant project retains local virtual environment packages.",
      recommendation: "Remove .venv if disk reclamation is desired; recreate with requirements.txt.",
      entities_involved: ["project:C:\\Users\\pc\\Desktop\\talib_ilm-main"],
      confidence: 0.95,
    },
  ],
  metadata: {
    scan_duration_ms: 342,
    engine_version: "0.1.0",
    timestamp: Date.now() / 1000,
    hostname: "DESKTOP-OQLTNEG",
    scan_roots: ["C:\\Users\\pc\\Desktop"],
  },
};

export const MOCK_SYSTEM_SPECS: SystemSpecsReport = {
  os: {
    product_name: "Windows 10 Home Single Language",
    version: "22H2",
    build: "19045.6466",
    arch: "AMD64",
    hostname: "DESKTOP-OQLTNEG",
  },
  pc: {
    manufacturer: "ASUSTeK COMPUTER INC.",
    model: "VivoBook_ASUSLaptop X515EP_X515EP",
  },
  cpu: {
    name: "11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz",
    physical_cores: 4,
    logical_cores: 8,
    current_freq_mhz: 2419.0,
    max_freq_mhz: 2419.0,
    percent: 18.4,
  },
  ram: {
    total_bytes: 16859107328,
    used_bytes: 10834378752,
    available_bytes: 6024728576,
    percent: 64.3,
    swap_total_bytes: 2550136832,
    swap_used_bytes: 145362944,
  },
  gpus: [
    {
      name: "Intel(R) Iris(R) Xe Graphics",
      adapter_ram_bytes: 1073741824,
      driver_version: "27.20.100.9268",
    },
    {
      name: "NVIDIA GeForce MX330",
      adapter_ram_bytes: 2147483648,
      driver_version: "32.0.15.8180",
    },
  ],
  battery: {
    has_battery: true,
    percent: 100,
    power_plugged: true,
  },
  uptime_seconds: 31463,
  uptime_formatted: "8h 44m",
  drives: [
    {
      mountpoint: "C:\\",
      device: "C:\\",
      label: "System",
      fstype: "NTFS",
      total_bytes: 385609023488,
      used_bytes: 321187192832,
      free_bytes: 64421830656,
      percent: 83.3,
      is_system: true,
      status: "healthy",
      media_type: "SSD",
      friendly_name: "INTEL SSDPEKNU512GZ",
    },
  ],
  physical_disks: [
    {
      device_id: "0",
      friendly_name: "INTEL SSDPEKNU512GZ",
      media_type: "SSD",
      bus_type: "NVMe",
      size_bytes: 512110190592,
    },
  ],
  raw_partitions: [
    { disk_number: 0, partition_number: 1, drive_letter: null, size_bytes: 104857600, partition_type: "System" },
    { disk_number: 0, partition_number: 2, drive_letter: null, size_bytes: 16777216, partition_type: "Reserved" },
    { disk_number: 0, partition_number: 3, drive_letter: "C", size_bytes: 385609024000, partition_type: "Basic" },
    { disk_number: 0, partition_number: 4, drive_letter: null, size_bytes: 547356672, partition_type: "Recovery" },
    { disk_number: 0, partition_number: 5, drive_letter: null, size_bytes: 53687091200, partition_type: "Unknown / Ext4" },
    { disk_number: 0, partition_number: 6, drive_letter: null, size_bytes: 17179869184, partition_type: "Unknown / Swap" },
    { disk_number: 0, partition_number: 7, drive_letter: null, size_bytes: 54962159616, partition_type: "Unknown" },
  ],
};

export const MOCK_LIVE_METRICS: LiveSystemMetrics = {
  cpu_percent: 14.2,
  ram_percent: 64.3,
  ram_used_bytes: 10834378752,
  ram_total_bytes: 16859107328,
  disk_read_bytes_sec: 142300,
  disk_write_bytes_sec: 845200,
  net_sent_bytes_sec: 1240,
  net_recv_bytes_sec: 48900,
  uptime_seconds: 31463,
  uptime_formatted: "8h 44m",
};

export const MOCK_STARTUP_PROGRAMS: StartupProgramItem[] = [
  {
    id: "hkcu:Discord",
    name: "Discord",
    command: '"C:\\Users\\pc\\AppData\\Local\\Discord\\Update.exe" --processStart Discord.exe',
    exe_path: "C:\\Users\\pc\\AppData\\Local\\Discord\\Update.exe",
    exists: true,
    is_enabled: true,
    scope: "user_registry",
    source: "HKCU\\Run",
    can_modify: true,
    impact: "high",
  },
  {
    id: "hkcu:Docker Desktop",
    name: "Docker Desktop",
    command: "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe",
    exe_path: "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe",
    exists: true,
    is_enabled: false,
    scope: "user_registry",
    source: "HKCU\\Run",
    can_modify: true,
    impact: "high",
  },
  {
    id: "hkcu:electron.app.Notion",
    name: "Notion",
    command: '"C:\\Users\\pc\\AppData\\Local\\Programs\\Notion\\Notion.exe" --open-at-login',
    exe_path: "C:\\Users\\pc\\AppData\\Local\\Programs\\Notion\\Notion.exe",
    exists: true,
    is_enabled: true,
    scope: "user_registry",
    source: "HKCU\\Run",
    can_modify: true,
    impact: "high",
  },
  {
    id: "hkcu:OneDrive",
    name: "OneDrive",
    command: '"C:\\Users\\pc\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe" /background',
    exe_path: "C:\\Users\\pc\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe",
    exists: true,
    is_enabled: true,
    scope: "user_registry",
    source: "HKCU\\Run",
    can_modify: true,
    impact: "low",
  },
  {
    id: "hkcu:ScreenRec",
    name: "ScreenRec",
    command: "C:\\Users\\pc\\AppData\\Local\\StreamingVideoProvider\\ScreenRec_app\\screenrec.exe",
    exe_path: "C:\\Users\\pc\\AppData\\Local\\StreamingVideoProvider\\ScreenRec_app\\screenrec.exe",
    exists: true,
    is_enabled: true,
    scope: "user_registry",
    source: "HKCU\\Run",
    can_modify: true,
    impact: "low",
  },
  {
    id: "hklm:SecurityHealth",
    name: "Windows Security",
    command: "%windir%\\system32\\SecurityHealthSystray.exe",
    exe_path: "C:\\Windows\\System32\\SecurityHealthSystray.exe",
    exists: true,
    is_enabled: true,
    scope: "system_registry",
    source: "HKLM\\Run",
    can_modify: false,
    impact: "low",
  },
];

export const MOCK_LARGE_FILES: LargeFileItem[] = [
  {
    path: "C:\\Users\\pc\\Desktop\\entropy\\dist\\Entropy-Setup-0.1.3.exe",
    name: "Entropy-Setup-0.1.3.exe",
    extension: ".exe",
    size_bytes: 22439526,
    last_modified: Date.now() / 1000 - 3600,
    category: "binary",
    workspace_root: "C:\\Users\\pc\\Desktop\\entropy",
    relative_path: "dist\\Entropy-Setup-0.1.3.exe",
  },
  {
    path: "C:\\Users\\pc\\Desktop\\entropy\\dist\\Entropy-Setup-0.1.2.exe",
    name: "Entropy-Setup-0.1.2.exe",
    extension: ".exe",
    size_bytes: 22439526,
    last_modified: Date.now() / 1000 - 86400,
    category: "binary",
    workspace_root: "C:\\Users\\pc\\Desktop\\entropy",
    relative_path: "dist\\Entropy-Setup-0.1.2.exe",
  },
  {
    path: "C:\\Users\\pc\\Desktop\\entropy\\dist\\Entropy-Setup-0.1.1.exe",
    name: "Entropy-Setup-0.1.1.exe",
    extension: ".exe",
    size_bytes: 22439526,
    last_modified: Date.now() / 1000 - 172800,
    category: "binary",
    workspace_root: "C:\\Users\\pc\\Desktop\\entropy",
    relative_path: "dist\\Entropy-Setup-0.1.1.exe",
  },
  {
    path: "C:\\Users\\pc\\Desktop\\entropy\\build\\Entropy\\Entropy.pkg",
    name: "Entropy.pkg",
    extension: ".pkg",
    size_bytes: 20328526,
    last_modified: Date.now() / 1000 - 3600,
    category: "binary",
    workspace_root: "C:\\Users\\pc\\Desktop\\entropy",
    relative_path: "build\\Entropy\\Entropy.pkg",
  },
  {
    path: "C:\\Users\\pc\\Desktop\\entropy\\.agents\\skills\\impeccable\\scripts\\bin\\windows-x64\\impeccable.exe",
    name: "impeccable.exe",
    extension: ".exe",
    size_bytes: 14720392,
    last_modified: Date.now() / 1000 - 500000,
    category: "binary",
    workspace_root: "C:\\Users\\pc\\Desktop\\entropy",
    relative_path: ".agents\\skills\\impeccable\\scripts\\bin\\windows-x64\\impeccable.exe",
  },
];

export const MOCK_INSTALLED_APPS: InstalledAppItem[] = [
  {
    id: "DaVinciResolve",
    name: "DaVinci Resolve",
    version: "18.6.5",
    publisher: "Blackmagic Design",
    install_date: "2024-02-14",
    size_bytes: 5261334937,
    size_formatted: "4.9 GB",
    install_location: "C:\\Program Files\\Blackmagic Design\\DaVinci Resolve",
    scope: "system",
    category: "media",
    can_uninstall: true,
    uninstall_command: "MsiExec.exe /I{B662C6E8-13DF-4811-A528-91F26FA93122}",
    is_dev_tool: false,
  },
  {
    id: "DockerDesktop",
    name: "Docker Desktop",
    version: "4.28.0",
    publisher: "Docker Inc.",
    install_date: "2024-01-20",
    size_bytes: 3543348019,
    size_formatted: "3.3 GB",
    install_location: "C:\\Program Files\\Docker\\Docker",
    scope: "system",
    category: "development",
    can_uninstall: true,
    uninstall_command: '"C:\\Program Files\\Docker\\Docker\\Docker Desktop Installer.exe" uninstall',
    is_dev_tool: true,
  },
  {
    id: "MicrosoftPowerBI",
    name: "Microsoft PowerBI Desktop (x64)",
    version: "2.126.927.0",
    publisher: "Microsoft Corporation",
    install_date: "2024-03-05",
    size_bytes: 3543348019,
    size_formatted: "3.3 GB",
    install_location: "C:\\Program Files\\Microsoft Power BI Desktop",
    scope: "system",
    category: "productivity",
    can_uninstall: true,
    uninstall_command: "MsiExec.exe /X{739C77F5-3DB7-440B-9721-DFB67B75F348}",
    is_dev_tool: false,
  },
  {
    id: "MicrosoftEdge",
    name: "Microsoft Edge",
    version: "123.0.2420.81",
    publisher: "Microsoft Corporation",
    install_date: "2024-03-28",
    size_bytes: 2254857830,
    size_formatted: "2.1 GB",
    install_location: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application",
    scope: "system",
    category: "browser",
    can_uninstall: false,
    uninstall_command: null,
    is_dev_tool: false,
  },
  {
    id: "MongoDB",
    name: "MongoDB 7.0.5 2008R2Plus SSL (64 bit)",
    version: "7.0.5",
    publisher: "MongoDB Inc.",
    install_date: "2024-01-10",
    size_bytes: 1717986918,
    size_formatted: "1.6 GB",
    install_location: "C:\\Program Files\\MongoDB\\Server\\7.0",
    scope: "system",
    category: "development",
    can_uninstall: true,
    uninstall_command: "MsiExec.exe /X{72D9D2E9-A512-4217-BF87-84C1C45B6C39}",
    is_dev_tool: true,
  },
  {
    id: "CursorUser",
    name: "Cursor (User)",
    version: "0.32.8",
    publisher: "Anysphere",
    install_date: "2024-04-12",
    size_bytes: 1181116006,
    size_formatted: "1.1 GB",
    install_location: "C:\\Users\\pc\\AppData\\Local\\Programs\\cursor",
    scope: "user",
    category: "development",
    can_uninstall: true,
    uninstall_command: '"C:\\Users\\pc\\AppData\\Local\\Programs\\cursor\\unins000.exe"',
    is_dev_tool: true,
  },
  {
    id: "AndroidStudio",
    name: "Android Studio",
    version: "2023.2.1",
    publisher: "Google LLC",
    install_date: "2024-02-18",
    size_bytes: 1073741824,
    size_formatted: "1.0 GB",
    install_location: "C:\\Program Files\\Android\\Android Studio",
    scope: "system",
    category: "development",
    can_uninstall: true,
    uninstall_command: '"C:\\Program Files\\Android\\Android Studio\\bin\\uninstall.exe"',
    is_dev_tool: true,
  },
  {
    id: "EclipseTemurinJDK17",
    name: "Eclipse Temurin JDK avec Hotspot 17.0.18+8 (x64)",
    version: "17.0.18.8",
    publisher: "Eclipse Adoptium",
    install_date: "2024-01-15",
    size_bytes: 350000000,
    size_formatted: "333.8 MB",
    install_location: "C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.18.8-hotspot",
    scope: "system",
    category: "development",
    can_uninstall: true,
    uninstall_command: "MsiExec.exe /I{7F38A7DE-8EF9-4672-8815-56B42D2D725C}",
    is_dev_tool: true,
  },
  {
    id: "Discord",
    name: "Discord",
    version: "1.0.9038",
    publisher: "Discord Inc.",
    install_date: "2024-03-01",
    size_bytes: 280000000,
    size_formatted: "267.0 MB",
    install_location: "C:\\Users\\pc\\AppData\\Local\\Discord",
    scope: "user",
    category: "communication",
    can_uninstall: true,
    uninstall_command: '"C:\\Users\\pc\\AppData\\Local\\Discord\\Update.exe" --uninstall -s',
    is_dev_tool: false,
  },
  {
    id: "Entropy",
    name: "Entropy",
    version: "0.1.2",
    publisher: "Entropy Team",
    install_date: "2024-04-15",
    size_bytes: 98000000,
    size_formatted: "93.5 MB",
    install_location: "C:\\Users\\pc\\AppData\\Local\\Programs\\Entropy",
    scope: "user",
    category: "utility",
    can_uninstall: true,
    uninstall_command: '"C:\\Users\\pc\\AppData\\Local\\Programs\\Entropy\\Uninstall Entropy.exe"',
    is_dev_tool: true,
  },
];

export const MOCK_DUPLICATE_REPORT: DuplicateReport = {
  total_groups: 2,
  total_duplicate_files: 5,
  total_wasted_bytes: 44879052,
  total_wasted_formatted: "42.8 MB",
  scanned_roots: ["C:\\Users\\pc\\Desktop\\entropy"],
  groups: [
    {
      group_id: "fa68f62052f77c65",
      file_size_bytes: 22439526,
      file_size_formatted: "21.4 MB",
      file_count: 2,
      wasted_bytes: 22439526,
      wasted_formatted: "21.4 MB",
      files: [
        {
          path: "C:\\Users\\pc\\Desktop\\entropy\\dist\\Entropy-Setup-0.1.3.exe",
          name: "Entropy-Setup-0.1.3.exe",
          extension: ".exe",
          size_bytes: 22439526,
          last_modified: Date.now() / 1000 - 3600,
          last_modified_formatted: "2024-04-15 14:30",
          relative_path: "dist\\Entropy-Setup-0.1.3.exe",
          workspace_root: "C:\\Users\\pc\\Desktop\\entropy",
        },
        {
          path: "C:\\Users\\pc\\Desktop\\entropy\\backup\\Entropy-Setup-0.1.3-copy.exe",
          name: "Entropy-Setup-0.1.3-copy.exe",
          extension: ".exe",
          size_bytes: 22439526,
          last_modified: Date.now() / 1000 - 86400,
          last_modified_formatted: "2024-04-14 10:15",
          relative_path: "backup\\Entropy-Setup-0.1.3-copy.exe",
          workspace_root: "C:\\Users\\pc\\Desktop\\entropy",
        },
      ],
    },
    {
      group_id: "3e8a912bb01c45d8",
      file_size_bytes: 11219763,
      file_size_formatted: "10.7 MB",
      file_count: 3,
      wasted_bytes: 22439526,
      wasted_formatted: "21.4 MB",
      files: [
        {
          path: "C:\\Users\\pc\\Desktop\\entropy\\assets\\bundle.tar.gz",
          name: "bundle.tar.gz",
          extension: ".gz",
          size_bytes: 11219763,
          last_modified: Date.now() / 1000 - 7200,
          last_modified_formatted: "2024-04-15 12:00",
          relative_path: "assets\\bundle.tar.gz",
          workspace_root: "C:\\Users\\pc\\Desktop\\entropy",
        },
        {
          path: "C:\\Users\\pc\\Desktop\\entropy\\temp\\bundle_copy.tar.gz",
          name: "bundle_copy.tar.gz",
          extension: ".gz",
          size_bytes: 11219763,
          last_modified: Date.now() / 1000 - 14400,
          last_modified_formatted: "2024-04-15 10:00",
          relative_path: "temp\\bundle_copy.tar.gz",
          workspace_root: "C:\\Users\\pc\\Desktop\\entropy",
        },
        {
          path: "C:\\Users\\pc\\Desktop\\entropy\\downloads\\bundle.tar.gz",
          name: "bundle.tar.gz",
          extension: ".gz",
          size_bytes: 11219763,
          last_modified: Date.now() / 1000 - 86400,
          last_modified_formatted: "2024-04-14 18:30",
          relative_path: "downloads\\bundle.tar.gz",
          workspace_root: "C:\\Users\\pc\\Desktop\\entropy",
        },
      ],
    },
  ],
};

